---
queries:
    - name: Tag Query
      file_path: queries/tag.gql
    - name: widget_query
      file_path: queries/widget_query.gql

# objects:
#   - objects/groups.yml

schemas:
  - schemas/widgets.yml

# generator_definitions:
#   - name: widget_generator
#     file_path: generators/widget_generator.py
#     targets: widgets
#     query: widget_query
#     convert_query_response: true
#     class_name: WidgetGenerator
#     parameters:
#       name: name__value
