---
queries:
  - name: tags_query
    file_path: queries/tags_query.gql

check_definitions:
  - name: check_color_tags_name
    class_name: ColorTagsCheck
    file_path: checks/tags_check.py
    targets: colored_tags # This specifies the group to target
    parameters:
      name: "name__value"
